name: Node20 Downloader
on:
  workflow_dispatch:
    inputs:
      url:
        description: 'YouTube URL'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install Tools
        run: |
          sudo curl -L https://github.com -o /usr/local/bin/yt-dlp
          sudo chmod a+rx /usr/local/bin/yt-dlp
      - name: Download
        run: yt-dlp -f "best" "${{ github.event.inputs.url }}"
      - name: Save to Storage
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Video Added" || echo "No changes"
          git push
